// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHdv1jT3AjHlh1Y_qMIqCfZKRFV2TgNt4',
    appId: '1:421873878289:web:5eec8ec557190dd46778b0',
    messagingSenderId: '421873878289',
    projectId: 'talk2me-ae41c',
    authDomain: 'talk2me-ae41c.firebaseapp.com',
    storageBucket: 'talk2me-ae41c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-l_GznfYxn-khcJhUiUnptZ8wMUskjI',
    appId: '1:421873878289:android:ef66632ea6b04a616778b0',
    messagingSenderId: '421873878289',
    projectId: 'talk2me-ae41c',
    storageBucket: 'talk2me-ae41c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oe-oQ00vrrw5c8bPYcc2g0i1jdTbf6E',
    appId: '1:421873878289:ios:88c9b3d204f00ef46778b0',
    messagingSenderId: '421873878289',
    projectId: 'talk2me-ae41c',
    storageBucket: 'talk2me-ae41c.appspot.com',
    iosBundleId: 'com.example.talktome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6oe-oQ00vrrw5c8bPYcc2g0i1jdTbf6E',
    appId: '1:421873878289:ios:edb5e93624ab4bd46778b0',
    messagingSenderId: '421873878289',
    projectId: 'talk2me-ae41c',
    storageBucket: 'talk2me-ae41c.appspot.com',
    iosBundleId: 'com.example.talktome.RunnerTests',
  );
}
